name: oclreid
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.1=py37h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=9.4.0=py37h6a678d5_0
  - pip=22.1.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pysocks=1.7.1=py37_1
  - python=3.7.16=h7a1cb2a_0
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py37h06a4308_0
  - setuptools=65.6.3=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - torchvision=0.12.0=py37_cu113
  - urllib3=1.26.14=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - addict==2.4.0
    - attributee==0.1.5
    - catkin-pkg==1.0.0
    - click==8.1.8
    - defusedxml==0.7.1
    - docopt==0.6.2
    - docutils==0.20.1
    - dotty-dict==1.3.1
    - easydict==1.13
    - fitlog==0.9.15
    - flask==2.2.5
    - genpy==2022.1
    - gitdb==4.0.12
    - gitpython==3.1.44
    - imageio==2.31.2
    - importlib-metadata==6.7.0
    - itsdangerous==2.1.2
    - jinja2==3.1.6
    - joblib==1.3.2
    - json-tricks==3.17.3
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - lap==0.5.12
    - llvmlite==0.36.0
    - loguru==0.5.3
    - markupsafe==2.1.5
    - mmcls==0.25.0
    - mmcv-full==1.5.3
    - mmdet==2.26.0
    - motmetrics==1.4.0
    - mpmath==1.3.0
    - networkx==2.6.3
    - numba==0.53.0
    - numpy==1.21.6
    - opencv-python==4.11.0.86
    - packaging==24.0
    - pandas==1.3.5
    - platformdirs==4.0.0
    - protobuf==4.24.4
    - python-dateutil==2.9.0.post0
    - pytools==2022.1.12
    - pytz==2025.2
    - pywavelets==1.3.0
    - pyyaml==6.0.1
    - rosnumpy==0.0.6.2
    - rospkg==1.6.0
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.2
    - shapely==2.0.7
    - smmap==5.0.2
    - sympy==1.10.1
    - tabulate==0.8.9
    - tensorboardx==2.6.2.2
    - terminaltables==3.1.10
    - thop==0.0.31-2005241907
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tomli==2.0.1
    - torchmetrics==0.11.4
    - tornado==6.2
    - tqdm==4.67.1
    - typing-extensions==4.7.1
    - visdom==0.2.4
    - websocket-client==1.6.1
    - werkzeug==2.2.3
    - xmltodict==0.14.2
    - yacs==0.1.8
    - yapf==0.43.0
    - zipp==3.15.0
prefix: /mnt/DATA/Arun/anaconda3/envs/oclreid
